version: "3"

services:
  chaskiq-redis:
    image: redis:7.0.11-alpine3.17
    ports:
      - "6379:6379"

  chaskiq-anycable-rpc:
    env_file:
      - ./chaskiq.env
    image: teleatiendo_chaskiq_test:v1.0
    ports:
      - "50051:50051"
    command: bundle exec anycable

  chaskiq-anycable:
    env_file:
      - ./chaskiq.env
    image: "anycable/anycable-go:1.0-alpine"
    ports:
      - "8080:8080"
    depends_on:
      - chaskiq-redis
      - chaskiq-anycable-rpc

  chaskiq-web:
    env_file:
      - ./chaskiq.env
    image: teleatiendo_chaskiq_test:v1.0
    ports:
      - "3000:3000"
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    depends_on:
      - chaskiq-redis
    volumes:
    - /srv/www:/var/storage_chaskiq

  chaskiq-job:
    env_file:
      - ./chaskiq.env
    image: teleatiendo_chaskiq_test:v1.0
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - chaskiq-redis

  chaskiq-nginx:
    image: nginx:1.24.0-alpine3.17
    volumes:
      - ./chaskiq_site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
